### ISSUE TITLE
Plugin doesn't works

### ISSUE THREAD

**Issue by SnowAndrey** [Spectrall368/Generator-1.19.4#1]
![Снимок экрана 2024-04-10 213623](https://github.com/Spectrall368/Generator-1.19.4/assets/166642353/e1372061-d570-4948-bb9a-4f7fad015f82)
![Снимок экрана 2024-04-10 213818](https://github.com/Spectrall368/Generator-1.19.4/assets/166642353/15116010-3bcc-4fd3-9f36-cf2070aa766d)
Just installed plugin and I met this problem. Idk what to do. Very hope that this issue will be fixed

**Comment by Spectrall368** [comment]
where did you download it from? (because I think you downloaded the source code and not the plugin)

**Comment by SnowAndrey** [comment]
From "Plugin downloads"
https://mcreator.net/plugin/105663/minecraft-forge-1194-java-editiondatapack-generator

**Comment by Spectrall368** [comment]
Fixed (re-download the plugin)

**Comment by Spectrall368** [comment]
write again here if it was resolved or not

**Comment by Spectrall368** [comment]
I uploaded the file again but the MCreator site seems to ignore it

**Comment by Spectrall368** [comment]
Try with this:
https://github.com/Spectrall368/Generator-1.19.4/releases/download/V1.0/generator-1.19.4-1.0-2024.1.zip

**Comment by SnowAndrey** [comment]
Now it working. Thank you
